### ISSUE TITLE
UpdateGeometrySRID - Errors when lowercase

### ISSUE THREAD

**Issue by gpetit** [orbisgis/h2gis#1123]
I'm creating the doc of the `UpdateGeometrySRID` function ([see code source](https://github.com/orbisgis/h2gis/blob/master/h2gis-functions/src/main/java/org/h2gis/functions/spatial/crs/UpdateGeometrySRID.java))

When executing this
```mysql
CREATE TABLE geo_point (the_geom GEOMETRY(POINT));
INSERT INTO geo_point VALUES('SRID=0;POINT(0 0)');
SELECT UpdateGeometrySRID('GEO_POINT','THE_GEOM',4326);
```
it works.
But if I write `THE_GEOM` in lowercase 
```mysql
...
SELECT UpdateGeometrySRID('GEO_POINT','the_geom',4326);
```
I have this error message
```
The SRID value must be greater or equal than 0; SQL statement:
SELECT UpdateGeometrySRID('geo_point', 'the_geom', 2154) [0-200] null/0 (Aide)
```

In the meantime, if I write the table name in lowercase too

```mysql
SELECT UpdateGeometrySRID('geo_point','THE_GEOM',4326);
```
... i have this error message
```
Table "geo_point" non trouvée
Table "geo_point" not found; SQL statement:
ALTER TABLE "geo_point" ALTER COLUMN THE_GEOM TYPE GEOMETRY(POINT,4326) USING ST_SetSRID(THE_GEOM,4326) [42102-200] 42S02/42102 (Aide)
```

So it seems that this function is not managing upper/lower case very well.

@ebocher @SPalominos

**Comment by ebocher** [comment]
Done

**Comment by gpetit** [comment]
Just made the test with the [build 1139](https://jenkins.orbisgis.org/job/H2GIS/1139/)

```mysql
SELECT UpdateGeometrySRID('GEO_POINT','the_geom',4326);
```
with `the_geom` in lowercase now runs well

----

But still have the issue when `tableName` is in lowercase
```mysql
SELECT UpdateGeometrySRID('geo_point','THE_GEOM',4326);
```

**Comment by ebocher** [comment]
Fixed

**Comment by katzyn** [comment]
In both H2 (with default settings) and PostgreSQL `"GEO_POINT"` and `"geo_point"` are different identifiers.

**Comment by ebocher** [comment]
Yes. We use the TableLocation class in H2GIS to set the good identifier according the db
